
name: neural-holography
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.11.8
  - cffi=1.12.3
  - cloudpickle=1.2.2
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.9.0
  - dbus=1.13.12
  - decorator=4.4.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.6.1
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libprotobuf=3.11.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.34.0
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.9.0
  - numba=0.51.2
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1h
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1.1
  - protobuf=3.11.1
  - pycparser=2.19
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - pytorch=1.7.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.16.2
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tbb=2020.3
  - tensorboardx=1.9
  - tk=8.6.8
  - toolz=0.10.0
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.3
  - typing_extensions=3.7.4.3
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - aotools==1.0.7
    - configargparse==1.7
    - absl-py==0.9.0
    - cachetools==4.1.0
    - chardet==3.0.4
    - configargparse==1.0
    - densenet==0.1.1
    - google-auth==1.14.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.6.0
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opencv-python==4.4.0.42
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfirmata==1.1.0
    - pyserial==3.5
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - zipp==3.1.0